#cloud-config
package_update: false
package_upgrade: false

write_files:
  - path: /etc/modules-load.d/br_netfilter.conf
    content: |
      br_netfilter

runcmd:
  - sudo swapoff -a
  - sudo cp /etc/fstab /etc/fstab_copy
  - sudo sed -i '/\bswap\b/s/^/#/' /etc/fstab

  - sudo modprobe br_netfilter
  - sudo sh -c 'echo "br_netfilter" > /etc/modules-load.d/br_netfilter.conf'

  - sudo firewall-cmd --zone=trusted --add-interface=cni0 --permanent
  - sudo firewall-cmd --add-port=8090/tcp --permanent
  - sudo firewall-cmd --add-port=10250/tcp --permanent
  - sudo firewall-cmd --add-port=10255/tcp --permanent
  - sudo firewall-cmd --add-port=8472/udp --permanent

  - sudo systemctl restart firewalld.service
