#cloud-config
package_update: true
package_upgrade: true

write_files:
  - path: /etc/modules-load.d/br_netfilter.conf
    content: |
      br_netfilter

runcmd:
  - sudo swapoff -a
  - sudo cp /etc/fstab /etc/fstab_copy
  - sudo sed -i '/\bswap\b/s/^/#/' /etc/fstab

  - sudo modprobe br_netfilter
  - sudo sh -c 'echo "br_netfilter" > /etc/modules-load.d/br_netfilter.conf'

  - sudo firewall-cmd --add-port=8091/tcp --permanent

  - sudo systemctl restart firewalld.service
